### ISSUE TITLE
Unable to capture opponent king

### ISSUE THREAD

**Issue by ngjunsiang** [recreationx/ChessGame#21]
https://github.com/recreationx/ChessGame/blob/32eeb383e620803a2eda9252a6806efa9b1871c2/chess.py#L249

## Steps to reproduce issue:
```
game = Board(debug=True)
game.start()
for start, end in [
                   ((4, 1), (4, 2)),
                   ((3, 6), (3, 5)),
                   ((3, 0), (7, 4)),
                   ((5, 6), (5, 5)), # check
                   ((7, 4), (4, 7)), # white win
                   ]:
    game.update(start, end)
    game.display()
    game.next_turn()
```
## Result
```
               ##               
        Proudly created by:     
            ZhengNan            
              Vina              
              SiYi              
             Bryan              
             David              

           [ column ]          
        0\1\2\3\4\5\6\7\       
 [row 7]♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ [row 7]
 [row 6]♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ [row 6]
 [row 5]                [row 5]
 [row 4]                [row 4]
 [row 3]                [row 3]
 [row 2]                [row 2]
 [row 1]♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ [row 1]
 [row 0]♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ [row 0]
        0/1/2/3/4/5/6/7/       
           [ column ]          
White player: 41 42
white pawn 41 -> 42
white player took 174.706848seconds to make a move.

           [ column ]          
        0\1\2\3\4\5\6\7\       
 [row 7]♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ [row 7]
 [row 6]♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ ♟︎ [row 6]
 [row 5]                [row 5]
 [row 4]                [row 4]
 [row 3]                [row 3]
 [row 2]        ♙       [row 2]
 [row 1]♙ ♙ ♙ ♙   ♙ ♙ ♙ [row 1]
 [row 0]♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ [row 0]
        0/1/2/3/4/5/6/7/       
           [ column ]          
Black player: 36 35
black pawn 36 -> 35
black player took 177.282857seconds to make a move.

           [ column ]          
        0\1\2\3\4\5\6\7\       
 [row 7]♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ [row 7]
 [row 6]♟︎ ♟︎ ♟︎   ♟︎ ♟︎ ♟︎ ♟︎ [row 6]
 [row 5]      ♟︎         [row 5]
 [row 4]                [row 4]
 [row 3]                [row 3]
 [row 2]        ♙       [row 2]
 [row 1]♙ ♙ ♙ ♙   ♙ ♙ ♙ [row 1]
 [row 0]♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ [row 0]
        0/1/2/3/4/5/6/7/       
           [ column ]          
White player: 30 74
white queen 30 -> 74
white player took 181.042094seconds to make a move.
black is in check!

           [ column ]          
        0\1\2\3\4\5\6\7\       
 [row 7]♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ [row 7]
 [row 6]♟︎ ♟︎ ♟︎   ♟︎ ♟︎ ♟︎ ♟︎ [row 6]
 [row 5]      ♟︎         [row 5]
 [row 4]              ♕ [row 4]
 [row 3]                [row 3]
 [row 2]        ♙       [row 2]
 [row 1]♙ ♙ ♙ ♙   ♙ ♙ ♙ [row 1]
 [row 0]♖ ♘ ♗   ♔ ♗ ♘ ♖ [row 0]
        0/1/2/3/4/5/6/7/       
           [ column ]          
Black player: 56 55
black pawn 56 -> 55
black player took 204.642204seconds to make a move.

           [ column ]          
        0\1\2\3\4\5\6\7\       
 [row 7]♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ [row 7]
 [row 6]♟︎ ♟︎ ♟︎   ♟︎   ♟︎ ♟︎ [row 6]
 [row 5]      ♟︎   ♟︎     [row 5]
 [row 4]              ♕ [row 4]
 [row 3]                [row 3]
 [row 2]        ♙       [row 2]
 [row 1]♙ ♙ ♙ ♙   ♙ ♙ ♙ [row 1]
 [row 0]♖ ♘ ♗   ♔ ♗ ♘ ♖ [row 0]
        0/1/2/3/4/5/6/7/       
           [ column ]          
White player: 74 47
white queen 74 -> 47
white player took 210.507101seconds to make a move.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/ChessGame/main.py", line 25, in <module>
    game.update(start, end)
  File "/home/runner/ChessGame/chess.py", line 226, in update
    self.check()
  File "/home/runner/ChessGame/chess.py", line 249, in check
    elif self.valid_move(coord, bkingcoord):
UnboundLocalError: local variable 'bkingcoord' referenced before assignment
```

**Comment by Vina071** [comment]
The issue should be fixed now
